name: Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0    # Fetch all history for Hugo .GitInfo and .Lastmod.

    - name: Nix
      uses: cachix/install-nix-action@v12

    - name: Deps
      run: nix-shell --pure --run 'npm i'

    - name: Hugo
      run: nix-shell --pure --run 'HUGO_ENV=production hugo --gc --minify'

    - name: CNAME
      run: echo 'martin.baillie.id' > public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

    - name: Purge Cloudflare Cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      if: env.CLOUDFLARE_TOKEN != null
